### ISSUE TITLE
Cannot load snapstho with v9.1

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/Dextromethorphan-Model#3]
@SRuedesh what version of the software has been used for the development? According to the publication, it is 9.1, but when I try  to load the snapshot in v9.1, I get the following error:

Information: Loading Project from snapshot file '...\Snapshots\v9.1\dextromethorphan_aggregated_simulations.json'
Warning: Snapshot is outdated and cannot be loaded for the following reason: 

Individual 'Gorski 2004 (96) PM, n=1 not found in project.
Error: Cannot load Simulation 'Gorski 2004 PM, 30 mg dextromethorphan hydromide (capsule/solution), n=1'
Information: Project loaded from snapshot

**Comment by SRuedesh** [comment]
Thanks @PavelBal for bringing that to my attention! The specified version is correct. Apparently, there was a broken link to the individual due to renaming prior to export. This seems to be both an oversight on my side and also a version-related issue. I am able to reproduce the broken link when using v9.1 but not when using v11.1 to export the snapshot from my file. I have fixed the snapshot, but can open an issue regarding the broken links, if that is desired.
